name: "Tempest documentation generation and publication"
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Envrionment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
      - name: Checkout Tempest
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Setup
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          sudo pip3 install --upgrade pip setuptools wheel
          pip3 install --user -r ./.github/requirements.txt
      - name: Build Docs
        shell: bash
        run: ./.github/build_docs.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          folder: _build
          clean: true
